import "./globals.css";
import "../styles/component.css";
import "../styles/animation.css";
import AuthProvider from "../context/AuthContext";
import DbProvider from "@/context/DbContext";

export const metadata = {
  title: "Prophecy Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Scheherazade+New:wght@400;700&family=Lato:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className="">
        <AuthProvider>
          <DbProvider>
            {children}
          </DbProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
